### ISSUE TITLE
Disable auto submit

### ISSUE THREAD

**Issue by niyue** [Ghasel/streamlit-ace#2]
Hi there,

I tried using streamlit-ace as the editor for SQL in my streamlit app and it works great for me. 

But compared to input like `st.text_area`, I find the streamlit-ace editor will automatically submit the query in the editor every time I change the query, for example, when I enter a query like `SELECT * FROM my_table`, the streamlit will be re-run every time when I type a character in the editor, which cause some unnecessary failed requests because the query is partial. I've no idea if this is caused by the streamlit component API or the streamlit-ace editor itself. Is there any way I can change this behavior to something like `st.text_area` so that I can manually apply the query using `Command + Enter` (I am using macOS) when the query is fully typed into the editor? Thanks.

**Comment by Ghasel** [comment]
Hello @niyue,

Using `Command + Enter` is indeed not supported currently due to how the component was implemented.
For your specific use case, you may try to create a streamlit button to manually apply/run your SQL query once you've finished inputting it.

**Comment by niyue** [comment]
Hi @Ghasel, thanks for the reply. I wonder how I can prevent the streamlit-ace component from automatically submit the query? I am not sure if this a question for streamlit in general or it is a specific streamlit-ace question, but currently it seems any typing in the ace component will trigger the refresh of the page, and I have no idea how to avoid this after checking out the options of the ace component.

**Comment by Ghasel** [comment]
Yes, for now there is no way to avoid the app to refresh when you input data with ace.
And from what you've said, I suppose each time the app refreshes, it runs your SQL query. As I said in my previous reply, instead of running your query each time the app reruns, you can run it only when you press a streamlit button, like so:

```python
query = st_ace(language="sql")

if st.button("Run query"):
    # Here is your logic to apply your SQL query
    execute_query(query)
```

**Comment by Ghasel** [comment]
Hello @niyue,

I've released a new version with an `auto_update` parameter. By setting it to `False`, you can use `Command + Enter` to manually update Streamlit.

**Comment by niyue** [comment]
@Ghasel thanks for the update. 

I gave it a try today, and found some issues, not really sure if I used it incorrect.
```
st_ace(
        ...
        min_lines=st.sidebar.slider("Min lines", value=10),
        # max_lines=st.sidebar.slider("Max lines", value=20),
        key="ace-editor",
        auto_update=False,
    )
```
I added the `auto_update` parameter and set it to `False`, but I found:
1) the prompt under the editor is `Press Ctrl+Enter to apply` while I use Safari under macOS, which I expect it to be `Press Cmd+Enter to apply` like regular text box
2) When I use `vim` or `emacs` keybindings, it works when I press `Cmd + Enter`, and the change is applied as expected
3) When I use `vscode` or `sublime` keybindings, and press `Cmd + Enter`, the change is not applied, instead, it works like `Enter` is pressed and a new line is inserted into the editor
4) Whatever keybinding I use, `Ctrl + Enter` doesn't work (and I assume it is not expected to work but the prompt is not correct as I said in issue no. 1)

**Comment by Ghasel** [comment]
@niyue Thanks for those details! Everything should work now with the version 0.0.3.

**Comment by xiashuqin89** [comment]
i have try to use auto_update parameters, but it still not work, do you have method to hide the submit button?
